# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: akhanye <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/05/30 10:25:20 by akhanye           #+#    #+#              #
#    Updated: 2017/08/25 16:37:02 by jngoma           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	libft.a

INCL	=	includes/


SRC		= 	$(INCL)ft_isalnum.c	\
			$(INCL)ft_isalpha.c	\
			$(INCL)ft_isdigit.c	\
			$(INCL)ft_isprint.c	\
			$(INCL)ft_putchar.c	\
			$(INCL)ft_putnbr.c		\
			$(INCL)ft_putstr.c		\
			$(INCL)ft_strcmp.c		\
			$(INCL)ft_strncmp.c	\
			$(INCL)ft_strcpy.c		\
			$(INCL)ft_strdup.c		\
			$(INCL)ft_strlen.c		\
			$(INCL)ft_tolower.c	\
			$(INCL)ft_toupper.c	\
			$(INCL)ft_atoi.c		\
			$(INCL)ft_strncpy.c	\
			$(INCL)ft_strstr.c		\
			$(INCL)ft_strcat.c		\
			$(INCL)ft_isnumbers.c	\
			$(INCL)ft_strncat.c	\
			$(INCL)ft_strchr.c		\
			$(INCL)ft_strrchr.c	\
			$(INCL)ft_memset.c		\
			$(INCL)ft_bzero.c		\
			$(INCL)ft_memcpy.c		\
			$(INCL)ft_printhex.c	\
			$(INCL)ft_memmove.c	\
			$(INCL)ft_memchr.c		\
			$(INCL)ft_memcmp.c		\
			$(INCL)ft_strtrim.c	\
			$(INCL)ft_strnstr.c	\
			$(INCL)ft_isascii.c	\
			$(INCL)ft_memccpy.c	\
			$(INCL)ft_strlcat.c	\
			$(INCL)ft_memalloc.c	\
			$(INCL)ft_memdel.c		\
			$(INCL)ft_strnew.c		\
			$(INCL)ft_strclr.c		\
			$(INCL)ft_striter.c	\
			$(INCL)ft_putcharmem.c	\
			$(INCL)ft_striteri.c	\
			$(INCL)ft_toupmem.c	\
			$(INCL)ft_strmap.c		\
			$(INCL)ft_strmapi.c	\
			$(INCL)ft_strequ.c		\
			$(INCL)ft_strnequ.c	\
			$(INCL)ft_strsub.c		\
			$(INCL)ft_strjoin.c	\
			$(INCL)ft_strsplit.c	\
			$(INCL)ft_digits.c		\
			$(INCL)ft_itoa.c		\
			$(INCL)ft_putendl.c	\
			$(INCL)ft_putchar_fd.c	\
			$(INCL)ft_putstr_fd.c	\
			$(INCL)ft_putendl_fd.c	\
			$(INCL)ft_putnbr_fd.c	\
			$(INCL)ft_strdel.c		\
			$(INCL)ft_memdup.c		\
			$(INCL)ft_lstnew.c		\
			$(INCL)ft_lstadd.c		\
			$(INCL)ft_lstdelone.c	\
			$(INCL)ft_lstdel.c		\
			$(INCL)ft_lstiter.c	\
			$(INCL)ft_lstmap.c		\
			$(INCL)ft_putline.c	\
			$(INCL)ft_skipempty.c	\
			$(INCL)ft_lastal.c		\
			$(INCL)ft_strcpysub.c	\
			$(INCL)ft_printallhex.c \
			$(INCL)get_next_line.c	\
			$(INCL)ft_abs.c			\
			$(INCL)ft_getlines.c	\
			$(INCL)ft_htoi.c		\
			$(INCL)ft_inarrayc.c	\
			$(INCL)ft_inarray.c		\
			$(INCL)ft_freestrsplit.c\
			$(INCL)ft_strdefix.c\
			$(INCL)ft_strdesplit.c\
			$(INCL)ft_strcuthead.c\
 			$(INCL)ft_addnbr.c\
 		 	$(INCL)destroy_fd.c\
			$(INCL)ft_is_number.c\
			$(INCL)ft_contains.c\
    			$(INCL)ft_destroy_2d.c\
			$(INCL)ft_htoi.c\
 			$(INCL)ft_items_in_grid.c\
 			$(INCL)ft_contains_str.c\
 			$(INCL)ft_out_of_int_range.c\
 			$(INCL)ft_strndup.c


OBJ		= 	ft_isalnum.o	\
			ft_isalpha.o	\
			ft_isdigit.o	\
			ft_isprint.o	\
			ft_putchar.o	\
			ft_putnbr.o		\
			ft_putstr.o		\
			ft_strcmp.o		\
			ft_strncmp.o	\
			ft_strcpy.o		\
			ft_strdup.o		\
			ft_strlen.o		\
			ft_tolower.o	\
			ft_toupper.o	\
			ft_atoi.o		\
			ft_strncpy.o	\
			ft_strstr.o		\
			ft_strcat.o		\
			ft_isnumbers.o	\
			ft_strncat.o	\
			ft_strchr.o		\
			ft_strrchr.o	\
			ft_memset.o		\
			ft_bzero.o		\
			ft_memcpy.o		\
			ft_printhex.o	\
			ft_memmove.o	\
			ft_memchr.o		\
			ft_memcmp.o		\
			ft_strtrim.o	\
			ft_strnstr.o	\
			ft_isascii.o	\
			ft_memccpy.o	\
			ft_strlcat.o	\
			ft_memalloc.o	\
			ft_memdel.o		\
			ft_strnew.o		\
			ft_strclr.o		\
			ft_striter.o	\
			ft_putcharmem.o	\
			ft_striteri.o	\
			ft_toupmem.o	\
			ft_strmap.o		\
			ft_strmapi.o	\
			ft_strequ.o		\
			ft_strnequ.o	\
			ft_strsub.o		\
			ft_strjoin.o	\
			ft_strsplit.o	\
			ft_digits.o		\
			ft_itoa.o		\
			ft_putendl.o	\
			ft_putchar_fd.o	\
			ft_putstr_fd.o	\
			ft_putendl_fd.o	\
			ft_putnbr_fd.o	\
			ft_strdel.o		\
			ft_memdup.o		\
			ft_lstnew.o		\
			ft_lstadd.o		\
			ft_lstdelone.o	\
			ft_lstdel.o		\
			ft_lstiter.o	\
			ft_lstmap.o		\
			ft_putline.o	\
			ft_skipempty.o	\
			ft_lastal.o		\
			ft_strcpysub.o	\
			ft_printallhex.o\
			get_next_line.o	\
			ft_abs.o		\
			ft_getlines.o	\
			ft_htoi.o		\
			ft_inarrayc.o	\
			ft_inarray.o		\
			ft_freestrsplit.o\
			ft_strdefix.o\
			ft_strdesplit.o\
			ft_strcuthead.o\
 			ft_addnbr.o\
 		 	destroy_fd.o\
			ft_is_number.o\
			ft_contains.o\
    			ft_destroy_2d.o\
			ft_htoi.o\
 			ft_items_in_grid.o\
 			ft_contains_str.o\
 			ft_out_of_int_range.o\
			ft_strndup.o


FLAGS	=	-Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	gcc  -c $(SRC) $(FLAGS)
	ar rc $(NAME) $(OBJ)
	ranlib $(NAME)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: 	fclean all
